spez/config/routes.rb
Rails.application.routes.draw do
  
  match '/home', to: 'pages#home', via: 'get'
  match '/contacts', to: 'pages#contacts', via: 'get'

  

end

spez/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

spez/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def zapravka 
  end

  def repair
  end

  def contacts
  end
end

spez/app/helpers/application_helper.rb
module ApplicationHelper
end

spez/app/helpers/pages_helper.rb
module PagesHelper
end

spez/app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <h1>Footer</h1>
  </div>
</nav>

spez/app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button> -->
              <a class="navbar-brand" href="#">Spez</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><%= link_to 'Home', home_path %></li>
                <li><a href="#about">About</a></li>
                <li><%= link_to 'Contacts', contacts_path %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>

spez/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spez</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>


<%= yield %>


<%= render 'layouts/footer' %>
</body>
</html>

spez/app/views/pages/contacts.html.erb
<h1>CONTACTS</h1>

spez/app/views/pages/home.html.erb
<h1> Home Page </h1>
<p>asdddddddddddddddddddddddd</p>